# Definition of various test suites
testsuite_1:
  test_configs:                 # You have to define at least one test_config
    - test1
  robots:                       # You have to define at least one robot
    - part25_250mm_ndtmatch
    - part25_350mm_ndtmatch
    - part25_500mm_ndtmatch
    - part25_600mm_ndtmatch
    - part25_750mm_ndtmatch
    - part25_1000mm_ndtmatch
    - part25_1500mm_ndtmatch
    - part50_250mm_ndtmatch
    - part50_350mm_ndtmatch
    - part50_500mm_ndtmatch
    - part50_600mm_ndtmatch
    - part50_750mm_ndtmatch
    - part50_1000mm_ndtmatch
    - part50_1500mm_ndtmatch
    - part75_250mm_ndtmatch
    - part75_350mm_ndtmatch
    - part75_500mm_ndtmatch
    - part75_600mm_ndtmatch
    - part75_750mm_ndtmatch
    - part75_1000mm_ndtmatch
    - part75_1500mm_ndtmatch
    - part100_250mm_ndtmatch
    - part100_350mm_ndtmatch
    - part100_500mm_ndtmatch
    - part100_600mm_ndtmatch
    - part100_750mm_ndtmatch
    - part100_1000mm_ndtmatch
    - part100_1500mm_ndtmatch
    - part150_250mm_ndtmatch
    - part150_350mm_ndtmatch
    - part150_500mm_ndtmatch
    - part150_600mm_ndtmatch
    - part150_750mm_ndtmatch
    - part150_1000mm_ndtmatch
    - part150_1500mm_ndtmatch
    - part200_250mm_ndtmatch
    - part200_350mm_ndtmatch
    - part200_500mm_ndtmatch
    - part200_600mm_ndtmatch
    - part200_750mm_ndtmatch
    - part200_1000mm_ndtmatch
    - part200_1500mm_ndtmatch
    - part500_250mm_ndtmatch
    - part500_350mm_ndtmatch
    - part500_500mm_ndtmatch
    - part500_600mm_ndtmatch
    - part500_750mm_ndtmatch
    - part500_1000mm_ndtmatch
    - part500_1500mm_ndtmatch
    - part25_250.0mm
    - part25_350.0mm
    - part25_500.0mm
    - part25_600.0mm
    - part25_750.0mm
    - part25_1000.0mm
    - part25_1500.0mm
    - part50_250.0mm
    - part50_350.0mm
    - part50_500.0mm
    - part50_600.0mm
    - part50_750.0mm
    - part50_1000.0mm
    - part50_1500.0mm
    - part75_250.0mm
    - part75_350.0mm
    - part75_500.0mm
    - part75_600.0mm
    - part75_750.0mm
    - part75_1000.0mm
    - part75_1500.0mm
    - part100_250.0mm
    - part100_350.0mm
    - part100_500.0mm
    - part100_600.0mm
    - part100_750.0mm
    - part100_1000.0mm
    - part100_1500.0mm
    - part150_250.0mm
    - part150_350.0mm
    - part150_500.0mm
    - part150_600.0mm
    - part150_750.0mm
    - part150_1000.0mm
    - part150_1500.0mm
    - part200_250.0mm
    - part200_350.0mm
    - part200_500.0mm
    - part200_600.0mm
    - part200_750.0mm
    - part200_1000.0mm
    - part200_1500.0mm
    - part500_250.0mm
    - part500_350.0mm
    - part500_500.0mm
    - part500_600.0mm
    - part500_750.0mm
    - part500_1000.0mm
    - part500_1500.0mm
  robot_envs:                   # You have to define at least one robot_env
    - env1
