scene_1:
  environment:
    additional_obstacles: []
    mesh: /files/rack.stl
    orientation: [90.0, 0.0, 90.0]
    position: [0.56, -0.64, 0.0]
    scaling: 0.002
  object:
    dimension: [0.02, 0.02, 0.1]
    shape: 3
  positions:
    arm: right
    goal_l: [0.594, 0.15, 1.082]
    goal_r: [0.564, 0.162, 0.841]
    start_r: [0.596, -0.332, 0.854]
    waypoints_l:
    - [0.403, 0.166, 0.843]
    - [0.41, 0.165, 1.067]
    waypoints_r:
    - [0.419, -0.17, 0.858]
    - [0.428, 0.071, 0.856]
scene_2:
  environment:
    additional_obstacles: []
    mesh: /files/shelf.stl
    orientation: [90.0, 0.0, 90.0]
    position: [0.67, -0.12, 0.16]
    scaling: 0.01
  object:
    dimension: [0.02, 0.02, 0.1]
    shape: 3
  positions:
    arm: right
    goal_l: [0.545, 0.021, 1.053]
    goal_r: [0.563, 0.027, 0.786]
    start_r: [0.569, -0.248, 0.789]
    waypoints_l:
    - [0.38, 0.01, 0.853]
    - [0.386, 0.01, 1.08]
    waypoints_r:
    - [0.416, -0.238, 0.784]
    - [0.428, 0.006, 0.775]
scene_3:
  environment:
    additional_obstacles:
    - id: wall_r
      orientation: [0.0, 0.0, 0.0]
      position: [0.8, -0.15, 0.86]
      shape: 1
      size: [0.48, 0.05, 0.5]
    - id: wall_l
      orientation: [0.0, 0.0, 0.0]
      position: [0.8, 0.15, 0.86]
      shape: 1
      size: [0.48, 0.05, 0.5]
    mesh: /files/table.stl
    orientation: [0.0, 0.0, 0.0]
    position: [0.56, 0.0, 0.61]
    scaling: 1.0
  object:
    dimension: [0.02, 0.02, 0.1]
    shape: 3
  poses: {approach: approach_3, drop: drop_3, end: end_3, grasp: grasp_3, lift: lift_3,
    move: move_3, retreat: retreat_3, start: start_3}
  positions:
    arm: right
    goal_l: [0.6333876252174377, 0.27723678946495056, 0.797934889793396]
    goal_r: [0.637124240398407, 0.0025927298702299595, 0.800425112247467]
    start_r: [0.6415619254112244, -0.2947347164154053, 0.8056684732437134]
    waypoints_l: []
    waypoints_r: []
