sudo: required
dist: trusty
# Force travis to use its minimal image with default Python settings
language: generic
compiler:
  - gcc

env:
  global:
    - CATKIN_WS=~/catkin_ws
    - CATKIN_WS_SRC=${CATKIN_WS}/src
    - CATKIN_WS_UNDERLAY=~/catkin_ws_underlay
    - CATKIN_WS_UNDERLAY_SRC=${CATKIN_WS_UNDERLAY}/src
    - CI_ROS_DISTRO="indigo"
    - DEFAULT_ROSINSTALL="https://raw.githubusercontent.com/ipa320/care-o-bot/${CI_ROS_DISTRO}_dev/.travis.rosinstall"

install:
  - wget https://raw.githubusercontent.com/ipa320/care-o-bot/${CI_ROS_DISTRO}_dev/.travis.install.sh
  - bash .travis.install.sh

script:
  - wget https://raw.githubusercontent.com/ipa320/care-o-bot/${CI_ROS_DISTRO}_dev/.travis.script.sh
  - bash .travis.script.sh

after_failure:
  - cd $CATKIN_WS
  - source devel/setup.bash
  - catkin_test_results --verbose
  - sudo apt-get install tree
  - tree $CATKIN_WS/build/atf/atf_test
  - tree /tmp/atf_test
  - ls -lh /tmp/atf_test/data/*.bag
  - rosbag info /tmp/atf_test/data/ts1_t1_1.bag
