test_1:
  planning_all:
    time:

  planning_1:
    time:
    resources:
      cpu: [move_group]
      mem: [move_group]

  planning_2:
    time:
    resources:
      cpu: [move_group]
      mem: [move_group]
      io: [move_group]
      network: [move_group]

  planning_3:
    time:
    resources:
      cpu: [move_group]
      mem: [move_group]

  execution_all:
    time:
    path_length:
      - [base_link, gripper_right_grasp_link]

  execution_1:
    time:
    resources:
      cpu: [move_group]
      mem: [move_group]

  execution_2:
    time:
    path_length:
      - [base_link, gripper_right_grasp_link]
      - [base_link, arm_right_3_link]
    resources:
      cpu: [move_group, grasping_app]
      mem: [move_group, grasping_app]

  execution_3:
    time:
    resources:
      cpu: [grasping_app]

test_2:
  execution_1:
    time:
    resources:
      cpu: [move_group]
      mem: [move_group]

  execution_2:
    time:
    path_length:
      - [base_link, gripper_right_grasp_link]
    resources:
      cpu: [move_group, grasping_app]
      mem: [move_group, grasping_app]

  execution_3:
    time:
    resources:
      cpu: [grasping_app]
