testsuite_1:
  scene_config: "scene_3"
  test_config: "test_1"
  robot: "cob4-2"
  planer_id:
    - "BKPIECEkConfigDefault"
    - "LBKPIECEkConfigDefault"
  planning_method:
    - "joint"
    - "cartesian_linear"
  jump_threshold:
    - 2
  eef_step:
    - 0.02
testsuite_2:
  scene_config: "scene_3"
  test_config: "test_2"
  robot: "cob4-2"
  planer_id:
    - "LBKPIECEkConfigDefault"
  planning_method:
    - "cartesian_linear"
  jump_threshold:
    - 1
    - 2
  eef_step:
    - 0.01