testsuite_1:
  scene_config: "scene_3"
  test_config: "test_1"
  robot: "cob4-2"
  planer_id:
    - "SBLkConfigDefault"
    - "ESTkConfigDefault"
    - "TRRTkConfigDefault"
  planning_method:
    - "joint"
  jump_threshold:
    - 2
  eef_step:
    - 0.02
testsuite_2:
  scene_config: "scene_3"
  test_config: "test_2"
  robot: "cob4-2"
  planer_id:
    - "RRTConnectkConfigDefault"
    - "PRMstarkConfigDefault"
    - "KPIECEkConfigDefault"
  planning_method:
    - "joint"
  jump_threshold:
    - 2
  eef_step:
    - 0.02
testsuite_3:
  scene_config: "scene_1"
  test_config: "test_2"
  robot: "cob4-2"
  planer_id:
    - "LBKPIECEkConfigDefault"
  planning_method:
    - "joint"
  jump_threshold:
    - 1
  eef_step:
    - 0.02