# without groundtruth, without global topics
testblock_small:
  time: []
  path_length:
    - topic: tf
      root_frame: link1
      measured_frame: link2
    - root_frame: link1
      measured_frame: link3
  publish_rate:
    - topic: topic1
    - topic: topic2
    - topic: topic3
testblock_large:
  time: []
  path_length:
    - topic: tf
      root_frame: link1
      measured_frame: link2
    - root_frame: link1
      measured_frame: link3
  publish_rate:
    - topic: /topic1
    - topic: /topic2
    - topic: /topic3
  interface:
    - node: publisher1
      publishers: 
        - [topic1, std_msgs/String]
    - node: publisher2
      publishers: 
        - [topic2, std_msgs/String]
# testblock_all empty
