# with groundtruth, with global topics
testblock_small:
  time:
    - groundtruth: 3
      groundtruth_epsilon: 0.5
  path_length:
    - topic: /tf
      root_frame: link1
      measured_frame: link2
      groundtruth: 6.28
      groundtruth_epsilon: 1.5
    - topic: /tf
      root_frame: link1
      measured_frame: link3
      groundtruth: 0.0
      groundtruth_epsilon: 1.5
  publish_rate:
    - topic: topic1
      groundtruth: 11
      groundtruth_epsilon: 5
    - topic: topic2
      groundtruth: 22
      groundtruth_epsilon: 5
    - topic: topic3
      groundtruth: 33
      groundtruth_epsilon: 5
    - topic: topic4
      groundtruth: 44
      groundtruth_epsilon: 5
    - topic: topic5
      groundtruth: 55
      groundtruth_epsilon: 5
    - topic: topic6
      groundtruth: 66
      groundtruth_epsilon: 5
    - topic: topic7
      groundtruth: 77
      groundtruth_epsilon: 5
    - topic: topic8
      groundtruth: 88
      groundtruth_epsilon: 5
    - topic: topic9
      groundtruth: 99
      groundtruth_epsilon: 5
testblock_large:
  time:
    - groundtruth: 5
      groundtruth_epsilon: 0.5
  path_length:
    - topic: /tf
      root_frame: link1
      measured_frame: link2
      groundtruth: 12.56
      groundtruth_epsilon: 1.5
    - topic: /tf
      root_frame: link1
      measured_frame: link3
      groundtruth: 0
      groundtruth_epsilon: 1.5
  publish_rate:
    - topic: /topic1
      groundtruth: 11
      groundtruth_epsilon: 5
    - topic: /topic2
      groundtruth: 22
      groundtruth_epsilon: 5
    - topic: /topic3
      groundtruth: 33
      groundtruth_epsilon: 5
    - topic: /topic4
      groundtruth: 44
      groundtruth_epsilon: 5
    - topic: /topic5
      groundtruth: 55
      groundtruth_epsilon: 5
    - topic: /topic6
      groundtruth: 66
      groundtruth_epsilon: 5
    - topic: /topic7
      groundtruth: 77
      groundtruth_epsilon: 5
    - topic: /topic8
      groundtruth: 88
      groundtruth_epsilon: 5
    - topic: /topic9
      groundtruth: 99
      groundtruth_epsilon: 5
  interface:
    - node: publisher1
      publishers: 
        - [topic1, std_msgs/String]
    - node: publisher2
      publishers: 
        - [topic2, std_msgs/String]
    - node: publisher3
      publishers: 
        - [topic3, std_msgs/String]
    - node: publisher4
      publishers: 
        - [topic4, std_msgs/String]
    - node: publisher5
      publishers: 
        - [topic5, std_msgs/String]
    - node: publisher6
      publishers: 
        - [topic6, std_msgs/String]
    - node: publisher7
      publishers: 
        - [topic7, std_msgs/String]
    - node: publisher8
      publishers: 
        - [topic8, std_msgs/String]
    - node: publisher9
      publishers: 
        - [topic9, std_msgs/String]
# testblock_all empty
