# example:
#   handler: ExampleParamHandler
interface:
    handler: CalculateInterfaceParamHandler
obstacle_distance:
  handler: CalculateDistanceToObstaclesParamHandler
path_length:
  handler: CalculatePathLengthParamHandler
publish_rate:
  handler: CalculatePublishRateParamHandler
resources:
  handler: CalculateResourcesParamHandler
time:
  handler: CalculateTimeParamHandler
user_result:
  handler: CalculateUserResultParamHandler
