time:
  handler: CalculateTimeParamHandler
path_length:
  handler: CalculatePathLengthParamHandler
distance:
  handler: CalculateDistanceParamHandler
resources:
  handler: CalculateResourcesParamHandler
obstacle_distance:
  handler: CalculateDistanceToObstaclesParamHandler
publish_rate:
  handler: CalculatePublishRateParamHandler
interface:
  handler: CalculateInterfaceParamHandler
localization:
  handler: CheckLocalizationParamHandler
# example:
#   handler: ExampleParamHandler
