# without groundtruth, without global topics
test_1:
  testblock_small:
    time:
    path_length:
      - root_frame: link1
        measured_frame: link2
      - root_frame: link1
        measured_frame: link3
    publish_rate:
      - topic: topic1
      - topic: topic2
      - topic: topic3
  testblock_large:
    time:
    path_length:
      - root_frame: link1
        measured_frame: link2
      - root_frame: link1
        measured_frame: link3
    publish_rate:
      - topic: /topic1
      - topic: /topic2
      - topic: /topic3
   # testblock_all empty

# with groundtruth, with global topics
test_2:
  testblock_small:
    time:
      - groundtruth: 3
        groundtruth_epsilon: 0.1
    path_length:
      - root_frame: link1
        measured_frame: link2
        groundtruth: 6.28
        groundtruth_epsilon: 0.1
      - root_frame: link1
        measured_frame: link3
        groundtruth: 0.0
        groundtruth_epsilon: 0.1
    publish_rate:
      - topic: topic1
        groundtruth: 11
        groundtruth_epsilon: 1
      - topic: topic2
        groundtruth: 22
        groundtruth_epsilon: 1
      - topic: topic3
        groundtruth: 33
        groundtruth_epsilon: 1
  testblock_large:
    time:
      - groundtruth: 5
        groundtruth_epsilon: 0.1
    path_length:
      - root_frame: link1
        measured_frame: link2
        groundtruth: 12.56
        groundtruth_epsilon: 0.1
      - root_frame: link1
        measured_frame: link3
        groundtruth: 0
        groundtruth_epsilon: 0.1
    publish_rate:
      - topic: /topic1
        groundtruth: 11
        groundtruth_epsilon: 1
      - topic: /topic2
        groundtruth: 22
        groundtruth_epsilon: 1
      - topic: /topic3
        groundtruth: 33
        groundtruth_epsilon: 1
  # testblock_all empty
