# Definition of various tests
test_1:
  testblock_1:
    time:
  testblock_2:
    time:
      groundtruth: 5
      groundtruth_epsilon: 0.1
    path_length:
      - [link1, link2]
      - [link1, link3]
test_2:
  testblock_1:
    time:
  testblock_3:
    time:
    path_length:
      - [link1, link2]
