- ts1_t1: {eef_step: 0.01, jump_threshold: 1, planer: SBLkConfigDefault, planning_method: cartesian_linear,
    robot: cob4-2, scene_config: scene_3, test_config: test_1}
- ts1_t2: {eef_step: 0.01, jump_threshold: 1, planer: SBLkConfigDefault, planning_method: joint,
    robot: cob4-2, scene_config: scene_3, test_config: test_1}
- ts1_t3: {eef_step: 0.01, jump_threshold: 1, planer: ESTkConfigDefault, planning_method: cartesian_linear,
    robot: cob4-2, scene_config: scene_3, test_config: test_1}
- ts1_t4: {eef_step: 0.01, jump_threshold: 1, planer: ESTkConfigDefault, planning_method: joint,
    robot: cob4-2, scene_config: scene_3, test_config: test_1}
- ts1_t5: {eef_step: 0.01, jump_threshold: 1, planer: LBKPIECEkConfigDefault, planning_method: cartesian_linear,
    robot: cob4-2, scene_config: scene_3, test_config: test_1}
- ts1_t6: {eef_step: 0.01, jump_threshold: 1, planer: LBKPIECEkConfigDefault, planning_method: joint,
    robot: cob4-2, scene_config: scene_3, test_config: test_1}
- ts1_t7: {eef_step: 0.01, jump_threshold: 2, planer: SBLkConfigDefault, planning_method: cartesian_linear,
    robot: cob4-2, scene_config: scene_3, test_config: test_1}
- ts1_t8: {eef_step: 0.01, jump_threshold: 2, planer: SBLkConfigDefault, planning_method: joint,
    robot: cob4-2, scene_config: scene_3, test_config: test_1}
- ts1_t9: {eef_step: 0.01, jump_threshold: 2, planer: ESTkConfigDefault, planning_method: cartesian_linear,
    robot: cob4-2, scene_config: scene_3, test_config: test_1}
- ts1_t10: {eef_step: 0.01, jump_threshold: 2, planer: ESTkConfigDefault, planning_method: joint,
    robot: cob4-2, scene_config: scene_3, test_config: test_1}
- ts1_t11: {eef_step: 0.01, jump_threshold: 2, planer: LBKPIECEkConfigDefault, planning_method: cartesian_linear,
    robot: cob4-2, scene_config: scene_3, test_config: test_1}
- ts1_t12: {eef_step: 0.01, jump_threshold: 2, planer: LBKPIECEkConfigDefault, planning_method: joint,
    robot: cob4-2, scene_config: scene_3, test_config: test_1}
- ts1_t13: {eef_step: 0.01, jump_threshold: 3, planer: SBLkConfigDefault, planning_method: cartesian_linear,
    robot: cob4-2, scene_config: scene_3, test_config: test_1}
- ts1_t14: {eef_step: 0.01, jump_threshold: 3, planer: SBLkConfigDefault, planning_method: joint,
    robot: cob4-2, scene_config: scene_3, test_config: test_1}
- ts1_t15: {eef_step: 0.01, jump_threshold: 3, planer: ESTkConfigDefault, planning_method: cartesian_linear,
    robot: cob4-2, scene_config: scene_3, test_config: test_1}
- ts1_t16: {eef_step: 0.01, jump_threshold: 3, planer: ESTkConfigDefault, planning_method: joint,
    robot: cob4-2, scene_config: scene_3, test_config: test_1}
- ts1_t17: {eef_step: 0.01, jump_threshold: 3, planer: LBKPIECEkConfigDefault, planning_method: cartesian_linear,
    robot: cob4-2, scene_config: scene_3, test_config: test_1}
- ts1_t18: {eef_step: 0.01, jump_threshold: 3, planer: LBKPIECEkConfigDefault, planning_method: joint,
    robot: cob4-2, scene_config: scene_3, test_config: test_1}
- ts1_t19: {eef_step: 0.02, jump_threshold: 1, planer: SBLkConfigDefault, planning_method: cartesian_linear,
    robot: cob4-2, scene_config: scene_3, test_config: test_1}
- ts1_t20: {eef_step: 0.02, jump_threshold: 1, planer: SBLkConfigDefault, planning_method: joint,
    robot: cob4-2, scene_config: scene_3, test_config: test_1}
- ts1_t21: {eef_step: 0.02, jump_threshold: 1, planer: ESTkConfigDefault, planning_method: cartesian_linear,
    robot: cob4-2, scene_config: scene_3, test_config: test_1}
- ts1_t22: {eef_step: 0.02, jump_threshold: 1, planer: ESTkConfigDefault, planning_method: joint,
    robot: cob4-2, scene_config: scene_3, test_config: test_1}
- ts1_t23: {eef_step: 0.02, jump_threshold: 1, planer: LBKPIECEkConfigDefault, planning_method: cartesian_linear,
    robot: cob4-2, scene_config: scene_3, test_config: test_1}
- ts1_t24: {eef_step: 0.02, jump_threshold: 1, planer: LBKPIECEkConfigDefault, planning_method: joint,
    robot: cob4-2, scene_config: scene_3, test_config: test_1}
- ts1_t25: {eef_step: 0.02, jump_threshold: 2, planer: SBLkConfigDefault, planning_method: cartesian_linear,
    robot: cob4-2, scene_config: scene_3, test_config: test_1}
- ts1_t26: {eef_step: 0.02, jump_threshold: 2, planer: SBLkConfigDefault, planning_method: joint,
    robot: cob4-2, scene_config: scene_3, test_config: test_1}
- ts1_t27: {eef_step: 0.02, jump_threshold: 2, planer: ESTkConfigDefault, planning_method: cartesian_linear,
    robot: cob4-2, scene_config: scene_3, test_config: test_1}
- ts1_t28: {eef_step: 0.02, jump_threshold: 2, planer: ESTkConfigDefault, planning_method: joint,
    robot: cob4-2, scene_config: scene_3, test_config: test_1}
- ts1_t29: {eef_step: 0.02, jump_threshold: 2, planer: LBKPIECEkConfigDefault, planning_method: cartesian_linear,
    robot: cob4-2, scene_config: scene_3, test_config: test_1}
- ts1_t30: {eef_step: 0.02, jump_threshold: 2, planer: LBKPIECEkConfigDefault, planning_method: joint,
    robot: cob4-2, scene_config: scene_3, test_config: test_1}
- ts1_t31: {eef_step: 0.02, jump_threshold: 3, planer: SBLkConfigDefault, planning_method: cartesian_linear,
    robot: cob4-2, scene_config: scene_3, test_config: test_1}
- ts1_t32: {eef_step: 0.02, jump_threshold: 3, planer: SBLkConfigDefault, planning_method: joint,
    robot: cob4-2, scene_config: scene_3, test_config: test_1}
- ts1_t33: {eef_step: 0.02, jump_threshold: 3, planer: ESTkConfigDefault, planning_method: cartesian_linear,
    robot: cob4-2, scene_config: scene_3, test_config: test_1}
- ts1_t34: {eef_step: 0.02, jump_threshold: 3, planer: ESTkConfigDefault, planning_method: joint,
    robot: cob4-2, scene_config: scene_3, test_config: test_1}
- ts1_t35: {eef_step: 0.02, jump_threshold: 3, planer: LBKPIECEkConfigDefault, planning_method: cartesian_linear,
    robot: cob4-2, scene_config: scene_3, test_config: test_1}
- ts1_t36: {eef_step: 0.02, jump_threshold: 3, planer: LBKPIECEkConfigDefault, planning_method: joint,
    robot: cob4-2, scene_config: scene_3, test_config: test_1}
- ts1_t37: {eef_step: 0.03, jump_threshold: 1, planer: SBLkConfigDefault, planning_method: cartesian_linear,
    robot: cob4-2, scene_config: scene_3, test_config: test_1}
- ts1_t38: {eef_step: 0.03, jump_threshold: 1, planer: SBLkConfigDefault, planning_method: joint,
    robot: cob4-2, scene_config: scene_3, test_config: test_1}
- ts1_t39: {eef_step: 0.03, jump_threshold: 1, planer: ESTkConfigDefault, planning_method: cartesian_linear,
    robot: cob4-2, scene_config: scene_3, test_config: test_1}
- ts1_t40: {eef_step: 0.03, jump_threshold: 1, planer: ESTkConfigDefault, planning_method: joint,
    robot: cob4-2, scene_config: scene_3, test_config: test_1}
- ts1_t41: {eef_step: 0.03, jump_threshold: 1, planer: LBKPIECEkConfigDefault, planning_method: cartesian_linear,
    robot: cob4-2, scene_config: scene_3, test_config: test_1}
- ts1_t42: {eef_step: 0.03, jump_threshold: 1, planer: LBKPIECEkConfigDefault, planning_method: joint,
    robot: cob4-2, scene_config: scene_3, test_config: test_1}
- ts1_t43: {eef_step: 0.03, jump_threshold: 2, planer: SBLkConfigDefault, planning_method: cartesian_linear,
    robot: cob4-2, scene_config: scene_3, test_config: test_1}
- ts1_t44: {eef_step: 0.03, jump_threshold: 2, planer: SBLkConfigDefault, planning_method: joint,
    robot: cob4-2, scene_config: scene_3, test_config: test_1}
- ts1_t45: {eef_step: 0.03, jump_threshold: 2, planer: ESTkConfigDefault, planning_method: cartesian_linear,
    robot: cob4-2, scene_config: scene_3, test_config: test_1}
- ts1_t46: {eef_step: 0.03, jump_threshold: 2, planer: ESTkConfigDefault, planning_method: joint,
    robot: cob4-2, scene_config: scene_3, test_config: test_1}
- ts1_t47: {eef_step: 0.03, jump_threshold: 2, planer: LBKPIECEkConfigDefault, planning_method: cartesian_linear,
    robot: cob4-2, scene_config: scene_3, test_config: test_1}
- ts1_t48: {eef_step: 0.03, jump_threshold: 2, planer: LBKPIECEkConfigDefault, planning_method: joint,
    robot: cob4-2, scene_config: scene_3, test_config: test_1}
- ts1_t49: {eef_step: 0.03, jump_threshold: 3, planer: SBLkConfigDefault, planning_method: cartesian_linear,
    robot: cob4-2, scene_config: scene_3, test_config: test_1}
- ts1_t50: {eef_step: 0.03, jump_threshold: 3, planer: SBLkConfigDefault, planning_method: joint,
    robot: cob4-2, scene_config: scene_3, test_config: test_1}
- ts1_t51: {eef_step: 0.03, jump_threshold: 3, planer: ESTkConfigDefault, planning_method: cartesian_linear,
    robot: cob4-2, scene_config: scene_3, test_config: test_1}
- ts1_t52: {eef_step: 0.03, jump_threshold: 3, planer: ESTkConfigDefault, planning_method: joint,
    robot: cob4-2, scene_config: scene_3, test_config: test_1}
- ts1_t53: {eef_step: 0.03, jump_threshold: 3, planer: LBKPIECEkConfigDefault, planning_method: cartesian_linear,
    robot: cob4-2, scene_config: scene_3, test_config: test_1}
- ts1_t54: {eef_step: 0.03, jump_threshold: 3, planer: LBKPIECEkConfigDefault, planning_method: joint,
    robot: cob4-2, scene_config: scene_3, test_config: test_1}
- ts2_t1: {eef_step: 0.09, jump_threshold: 4, planer: TRRTkConfigDefault, planning_method: cartesian,
    robot: cob4-2, scene_config: scene_2, test_config: test_3}
- ts2_t2: {eef_step: 0.09, jump_threshold: 4, planer: TRRTkConfigDefault, planning_method: cartesian_mixed,
    robot: cob4-2, scene_config: scene_2, test_config: test_3}
- ts2_t3: {eef_step: 0.09, jump_threshold: 4, planer: PRMkConfigDefault, planning_method: cartesian,
    robot: cob4-2, scene_config: scene_2, test_config: test_3}
- ts2_t4: {eef_step: 0.09, jump_threshold: 4, planer: PRMkConfigDefault, planning_method: cartesian_mixed,
    robot: cob4-2, scene_config: scene_2, test_config: test_3}
- ts2_t5: {eef_step: 0.09, jump_threshold: 4, planer: PRMstarkConfigDefault, planning_method: cartesian,
    robot: cob4-2, scene_config: scene_2, test_config: test_3}
- ts2_t6: {eef_step: 0.09, jump_threshold: 4, planer: PRMstarkConfigDefault, planning_method: cartesian_mixed,
    robot: cob4-2, scene_config: scene_2, test_config: test_3}
- ts2_t7: {eef_step: 0.09, jump_threshold: 6, planer: TRRTkConfigDefault, planning_method: cartesian,
    robot: cob4-2, scene_config: scene_2, test_config: test_3}
- ts2_t8: {eef_step: 0.09, jump_threshold: 6, planer: TRRTkConfigDefault, planning_method: cartesian_mixed,
    robot: cob4-2, scene_config: scene_2, test_config: test_3}
- ts2_t9: {eef_step: 0.09, jump_threshold: 6, planer: PRMkConfigDefault, planning_method: cartesian,
    robot: cob4-2, scene_config: scene_2, test_config: test_3}
- ts2_t10: {eef_step: 0.09, jump_threshold: 6, planer: PRMkConfigDefault, planning_method: cartesian_mixed,
    robot: cob4-2, scene_config: scene_2, test_config: test_3}
- ts2_t11: {eef_step: 0.09, jump_threshold: 6, planer: PRMstarkConfigDefault, planning_method: cartesian,
    robot: cob4-2, scene_config: scene_2, test_config: test_3}
- ts2_t12: {eef_step: 0.09, jump_threshold: 6, planer: PRMstarkConfigDefault, planning_method: cartesian_mixed,
    robot: cob4-2, scene_config: scene_2, test_config: test_3}
- ts2_t13: {eef_step: 0.09, jump_threshold: 8, planer: TRRTkConfigDefault, planning_method: cartesian,
    robot: cob4-2, scene_config: scene_2, test_config: test_3}
- ts2_t14: {eef_step: 0.09, jump_threshold: 8, planer: TRRTkConfigDefault, planning_method: cartesian_mixed,
    robot: cob4-2, scene_config: scene_2, test_config: test_3}
- ts2_t15: {eef_step: 0.09, jump_threshold: 8, planer: PRMkConfigDefault, planning_method: cartesian,
    robot: cob4-2, scene_config: scene_2, test_config: test_3}
- ts2_t16: {eef_step: 0.09, jump_threshold: 8, planer: PRMkConfigDefault, planning_method: cartesian_mixed,
    robot: cob4-2, scene_config: scene_2, test_config: test_3}
- ts2_t17: {eef_step: 0.09, jump_threshold: 8, planer: PRMstarkConfigDefault, planning_method: cartesian,
    robot: cob4-2, scene_config: scene_2, test_config: test_3}
- ts2_t18: {eef_step: 0.09, jump_threshold: 8, planer: PRMstarkConfigDefault, planning_method: cartesian_mixed,
    robot: cob4-2, scene_config: scene_2, test_config: test_3}
- ts2_t19: {eef_step: 0.06, jump_threshold: 4, planer: TRRTkConfigDefault, planning_method: cartesian,
    robot: cob4-2, scene_config: scene_2, test_config: test_3}
- ts2_t20: {eef_step: 0.06, jump_threshold: 4, planer: TRRTkConfigDefault, planning_method: cartesian_mixed,
    robot: cob4-2, scene_config: scene_2, test_config: test_3}
- ts2_t21: {eef_step: 0.06, jump_threshold: 4, planer: PRMkConfigDefault, planning_method: cartesian,
    robot: cob4-2, scene_config: scene_2, test_config: test_3}
- ts2_t22: {eef_step: 0.06, jump_threshold: 4, planer: PRMkConfigDefault, planning_method: cartesian_mixed,
    robot: cob4-2, scene_config: scene_2, test_config: test_3}
- ts2_t23: {eef_step: 0.06, jump_threshold: 4, planer: PRMstarkConfigDefault, planning_method: cartesian,
    robot: cob4-2, scene_config: scene_2, test_config: test_3}
- ts2_t24: {eef_step: 0.06, jump_threshold: 4, planer: PRMstarkConfigDefault, planning_method: cartesian_mixed,
    robot: cob4-2, scene_config: scene_2, test_config: test_3}
- ts2_t25: {eef_step: 0.06, jump_threshold: 6, planer: TRRTkConfigDefault, planning_method: cartesian,
    robot: cob4-2, scene_config: scene_2, test_config: test_3}
- ts2_t26: {eef_step: 0.06, jump_threshold: 6, planer: TRRTkConfigDefault, planning_method: cartesian_mixed,
    robot: cob4-2, scene_config: scene_2, test_config: test_3}
- ts2_t27: {eef_step: 0.06, jump_threshold: 6, planer: PRMkConfigDefault, planning_method: cartesian,
    robot: cob4-2, scene_config: scene_2, test_config: test_3}
- ts2_t28: {eef_step: 0.06, jump_threshold: 6, planer: PRMkConfigDefault, planning_method: cartesian_mixed,
    robot: cob4-2, scene_config: scene_2, test_config: test_3}
- ts2_t29: {eef_step: 0.06, jump_threshold: 6, planer: PRMstarkConfigDefault, planning_method: cartesian,
    robot: cob4-2, scene_config: scene_2, test_config: test_3}
- ts2_t30: {eef_step: 0.06, jump_threshold: 6, planer: PRMstarkConfigDefault, planning_method: cartesian_mixed,
    robot: cob4-2, scene_config: scene_2, test_config: test_3}
- ts2_t31: {eef_step: 0.06, jump_threshold: 8, planer: TRRTkConfigDefault, planning_method: cartesian,
    robot: cob4-2, scene_config: scene_2, test_config: test_3}
- ts2_t32: {eef_step: 0.06, jump_threshold: 8, planer: TRRTkConfigDefault, planning_method: cartesian_mixed,
    robot: cob4-2, scene_config: scene_2, test_config: test_3}
- ts2_t33: {eef_step: 0.06, jump_threshold: 8, planer: PRMkConfigDefault, planning_method: cartesian,
    robot: cob4-2, scene_config: scene_2, test_config: test_3}
- ts2_t34: {eef_step: 0.06, jump_threshold: 8, planer: PRMkConfigDefault, planning_method: cartesian_mixed,
    robot: cob4-2, scene_config: scene_2, test_config: test_3}
- ts2_t35: {eef_step: 0.06, jump_threshold: 8, planer: PRMstarkConfigDefault, planning_method: cartesian,
    robot: cob4-2, scene_config: scene_2, test_config: test_3}
- ts2_t36: {eef_step: 0.06, jump_threshold: 8, planer: PRMstarkConfigDefault, planning_method: cartesian_mixed,
    robot: cob4-2, scene_config: scene_2, test_config: test_3}
- ts2_t37: {eef_step: 0.03, jump_threshold: 4, planer: TRRTkConfigDefault, planning_method: cartesian,
    robot: cob4-2, scene_config: scene_2, test_config: test_3}
- ts2_t38: {eef_step: 0.03, jump_threshold: 4, planer: TRRTkConfigDefault, planning_method: cartesian_mixed,
    robot: cob4-2, scene_config: scene_2, test_config: test_3}
- ts2_t39: {eef_step: 0.03, jump_threshold: 4, planer: PRMkConfigDefault, planning_method: cartesian,
    robot: cob4-2, scene_config: scene_2, test_config: test_3}
- ts2_t40: {eef_step: 0.03, jump_threshold: 4, planer: PRMkConfigDefault, planning_method: cartesian_mixed,
    robot: cob4-2, scene_config: scene_2, test_config: test_3}
- ts2_t41: {eef_step: 0.03, jump_threshold: 4, planer: PRMstarkConfigDefault, planning_method: cartesian,
    robot: cob4-2, scene_config: scene_2, test_config: test_3}
- ts2_t42: {eef_step: 0.03, jump_threshold: 4, planer: PRMstarkConfigDefault, planning_method: cartesian_mixed,
    robot: cob4-2, scene_config: scene_2, test_config: test_3}
- ts2_t43: {eef_step: 0.03, jump_threshold: 6, planer: TRRTkConfigDefault, planning_method: cartesian,
    robot: cob4-2, scene_config: scene_2, test_config: test_3}
- ts2_t44: {eef_step: 0.03, jump_threshold: 6, planer: TRRTkConfigDefault, planning_method: cartesian_mixed,
    robot: cob4-2, scene_config: scene_2, test_config: test_3}
- ts2_t45: {eef_step: 0.03, jump_threshold: 6, planer: PRMkConfigDefault, planning_method: cartesian,
    robot: cob4-2, scene_config: scene_2, test_config: test_3}
- ts2_t46: {eef_step: 0.03, jump_threshold: 6, planer: PRMkConfigDefault, planning_method: cartesian_mixed,
    robot: cob4-2, scene_config: scene_2, test_config: test_3}
- ts2_t47: {eef_step: 0.03, jump_threshold: 6, planer: PRMstarkConfigDefault, planning_method: cartesian,
    robot: cob4-2, scene_config: scene_2, test_config: test_3}
- ts2_t48: {eef_step: 0.03, jump_threshold: 6, planer: PRMstarkConfigDefault, planning_method: cartesian_mixed,
    robot: cob4-2, scene_config: scene_2, test_config: test_3}
- ts2_t49: {eef_step: 0.03, jump_threshold: 8, planer: TRRTkConfigDefault, planning_method: cartesian,
    robot: cob4-2, scene_config: scene_2, test_config: test_3}
- ts2_t50: {eef_step: 0.03, jump_threshold: 8, planer: TRRTkConfigDefault, planning_method: cartesian_mixed,
    robot: cob4-2, scene_config: scene_2, test_config: test_3}
- ts2_t51: {eef_step: 0.03, jump_threshold: 8, planer: PRMkConfigDefault, planning_method: cartesian,
    robot: cob4-2, scene_config: scene_2, test_config: test_3}
- ts2_t52: {eef_step: 0.03, jump_threshold: 8, planer: PRMkConfigDefault, planning_method: cartesian_mixed,
    robot: cob4-2, scene_config: scene_2, test_config: test_3}
- ts2_t53: {eef_step: 0.03, jump_threshold: 8, planer: PRMstarkConfigDefault, planning_method: cartesian,
    robot: cob4-2, scene_config: scene_2, test_config: test_3}
- ts2_t54: {eef_step: 0.03, jump_threshold: 8, planer: PRMstarkConfigDefault, planning_method: cartesian_mixed,
    robot: cob4-2, scene_config: scene_2, test_config: test_3}
